import {FilterFragment} from "./filterFragment";
import {UnicodeFragment} from "./unicodeFragment";
import {CharacterUseFragment as UsageFragment} from "./usageFragment";
import {FavoritesFragment} from "./favoritesFragment";
import {MetaFragment} from "./metaFragment";
import { DataFragment } from "./dataFragment";

/**
 * Generic structure of `data.json`
 */
export interface SaveDataOf<T> {
    /**
     * Metadata information about the save data itself
     */
    meta: T;

    /**
     * Filtering of downloaded/displayed codepoints
     */
    filter: T;

    /**
     * Local character database
     */
    characters: T;

    /**
     * Usage information generated by the user
     */
    usage: T;

    /**
     * Favorites saved manually by the user
     */
    favorites: T;
}

/**
 * Structure of `data.json`, where each fragment is a self-managed data fragment
 */
export interface SaveData extends SaveDataOf<DataFragment> {
    meta: MetaFragment;
    filter: FilterFragment;
    characters: UnicodeFragment;
    usage: UsageFragment;
    favorites: FavoritesFragment;
}
