name: Build plugin

on:
  push:
    branches:
      - "release/[0-9]+.[0-9]+.[0-9]+"

env:
  PLUGIN_NAME: "unicode-search"
  BUILD_DIR: "./dist"
  RELEASE_VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: NPM Install and build
        run: |
          npm clean-install
          npm run build --if-present

      - name: ZIP build output
        working-directory: ${{ env.BUILD_DIR }}
        run: |
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
