name: Build obsidian plugin

on:
  push:
    branches:
      - "feature/github-actions"

ENV:
  PLUGIN_NAME: "obsidian-unicode-search"
  BUILD_DIR: "./dist"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: NPM Install, Build
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: |
          npm clean-install
          npm run build --if-present

      - name: ZIP build output
        working-directory: ${{ ENV.BUILD_DIR }}
        run: |
          zip -r ${{ ENV.PLUGIN_NAME }}.zip ${{ ENV.PLUGIN_NAME }}
